repos:
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
    - id: black-jupyter
      language_version: python3 # Should be a command that runs python3.6+
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
      name: isort (python)
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-json
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: requirements-txt-fixer
    - id: detect-aws-credentials
    - id: check-added-large-files
      args: ['--maxkb=5000', '--enforce-all']