[tool.isort]
profile = "black"
src_paths = ["isort", "test"]
skip = [".venv"]

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include_trailing_comma = "True"
use_parentheses = "True"
ensure_newline_before_comments = "True"
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

